package immerle

// This file declares the request/response shapes used purely for OpenAPI
// documentation (generated by swaggo/swag v2). The handlers serialize plain
// maps for flexibility; these typed structs give the generated spec precise
// schemas. They are intentionally not used at runtime.
//
// Responses carry the resource directly (no envelope). Errors use the apiError
// shape declared in respond.go.

// ThemeDTO is a user's UI theme.
type ThemeDTO struct {
	AccentColor string `json:"accentColor,omitempty" example:"#3b82f6"`
}

// ProviderDTO is a managed on-demand provider (built-in or dynamic).
type ProviderDTO struct {
	Name      string `json:"name" example:"manual"`
	Kind      string `json:"kind" example:"http"`
	Endpoint  string `json:"endpoint" example:"https://my-service.internal"`
	Config    string `json:"config" example:"{\"headers\":{\"Authorization\":\"Bearer x\"}}"`
	Enabled   bool   `json:"enabled" example:"true"`
	Active    bool   `json:"active" example:"true"`
	Builtin   bool   `json:"builtin" example:"false"`
	Deletable bool   `json:"deletable" example:"true"`
	SortOrder int    `json:"sortOrder" example:"3"`
}

// RuntimeSettingsDTO mirrors the admin-managed runtime settings.
type RuntimeSettingsDTO struct {
	Server struct {
		CORSAllowedOrigins []string `json:"corsAllowedOrigins" example:"*"`
	} `json:"server"`
	Auth struct {
		DeviceTokenTTLSeconds int `json:"deviceTokenTtlSeconds" example:"2592000"`
	} `json:"auth"`
	Transcode struct {
		FFmpegPath  string `json:"ffmpegPath" example:"ffmpeg"`
		FFprobePath string `json:"ffprobePath" example:"ffprobe"`
		Profiles    []struct {
			Name       string `json:"name" example:"mp3"`
			Format     string `json:"format" example:"mp3"`
			BitRate    int    `json:"bitRate" example:"192"`
			FFmpegArgs string `json:"ffmpegArgs,omitempty"`
		} `json:"profiles"`
	} `json:"transcode"`
	Providers struct {
		AutoDownloadOnPlay   bool `json:"autoDownloadOnPlay" example:"true"`
		SearchTimeoutSeconds int  `json:"searchTimeoutSeconds" example:"6"`
	} `json:"providers"`
	Scan struct {
		IntervalSeconds int  `json:"intervalSeconds" example:"3600"`
		Watch           bool `json:"watch" example:"true"`
	} `json:"scan"`
	Cleanup struct {
		Enabled         bool `json:"enabled" example:"true"`
		MaxAgeSeconds   int  `json:"maxAgeSeconds" example:"2592000"`
		IntervalSeconds int  `json:"intervalSeconds" example:"21600"`
	} `json:"cleanup"`
	Federation struct {
		Enabled             bool   `json:"enabled" example:"false"`
		HubURL              string `json:"hubUrl"`
		PublicKey           string `json:"publicKey"`
		PrivateKey          string `json:"privateKey"`
		SyncIntervalSeconds int    `json:"syncIntervalSeconds" example:"3600"`
		ResolveMissing      bool   `json:"resolveMissing"`
		ExportScrobbles     bool   `json:"exportScrobbles"`
	} `json:"federation"`
}

// SettingsDTO returns the runtime settings and restart state.
type SettingsDTO struct {
	Settings        RuntimeSettingsDTO `json:"settings"`
	RestartRequired bool               `json:"restartRequired" example:"false"`
	PendingRestart  []string           `json:"pendingRestart"`
}

// CleanupStatusDTO reports the provider-download eviction sweep state.
type CleanupStatusDTO struct {
	Enabled         bool  `json:"enabled" example:"true"`
	MaxAgeSeconds   int64 `json:"maxAgeSeconds" example:"2592000"`
	IntervalSeconds int64 `json:"intervalSeconds" example:"21600"`
}

// CleanupRunDTO reports the result of an on-demand eviction sweep.
type CleanupRunDTO struct {
	Removed int `json:"removed" example:"3"`
}

// CapabilityDTO describes one supported capability.
type CapabilityDTO struct {
	Version int `json:"version" example:"1"`
}

// CapabilitiesDTO is the capability-discovery payload.
type CapabilitiesDTO struct {
	Server          string                   `json:"server" example:"immerle"`
	ProtocolVersion string                   `json:"protocolVersion" example:"1.0.0"`
	Capabilities    map[string]CapabilityDTO `json:"capabilities"`
}

// SetupStatusDTO reports first-run setup state.
type SetupStatusDTO struct {
	Initialized        bool `json:"initialized" example:"false"`
	NeedsSetup         bool `json:"needsSetup" example:"true"`
	UserCount          int  `json:"userCount" example:"0"`
	SetupTokenRequired bool `json:"setupTokenRequired" example:"false"`
}

// SetupInitRequest creates the first administrator account.
type SetupInitRequest struct {
	Username string `json:"username" example:"kilian"`
	Password string `json:"password" example:"a-strong-password"`
	Email    string `json:"email,omitempty" example:"me@example.com"`
	// DisplayName is an optional free-text name shown in the UI (falls back to
	// the username when empty).
	DisplayName string `json:"displayName,omitempty" example:"Kilian Smiti"`
	// SetupToken is required only when the server was started with
	// auth.require_setup_token=true.
	SetupToken string `json:"setupToken,omitempty"`
}

// UserDTO is a public user representation.
type UserDTO struct {
	ID          string `json:"id"`
	Username    string `json:"username" example:"kilian"`
	DisplayName string `json:"displayName,omitempty" example:"Kilian Smiti"`
	IsAdmin     bool   `json:"isAdmin" example:"true"`
}

// AccountDTO is the caller's own account (includes the private email).
type AccountDTO struct {
	ID          string `json:"id"`
	Username    string `json:"username" example:"bob"`
	DisplayName string `json:"displayName,omitempty" example:"Bob Marley"`
	Email       string `json:"email,omitempty" example:"bob@example.com"`
	IsAdmin     bool   `json:"isAdmin" example:"false"`
	Language    string `json:"language,omitempty" example:"fr"`
}

// FriendDTO is a friend reference.
type FriendDTO struct {
	ID          string `json:"id"`
	Username    string `json:"username" example:"bob"`
	DisplayName string `json:"displayName,omitempty" example:"Bob Marley"`
}

// PendingFriendDTO is an incoming friend request.
type PendingFriendDTO struct {
	ID          string `json:"id"`
	Username    string `json:"username" example:"alice"`
	DisplayName string `json:"displayName,omitempty" example:"Alice Coltrane"`
	Since       string `json:"since" example:"2026-06-15T09:00:00Z"`
}

// ActivityItemDTO carries resolved, human-readable details about the item an
// activity event references (fields depend on itemType; empty when unresolved).
type ActivityItemDTO struct {
	Title    string `json:"title,omitempty" example:"One More Time"`
	Artist   string `json:"artist,omitempty" example:"Daft Punk"`
	Album    string `json:"album,omitempty" example:"Discovery"`
	AlbumID  string `json:"albumId,omitempty"`
	ArtistID string `json:"artistId,omitempty"`
	CoverArt string `json:"coverArt,omitempty"`
	Duration int    `json:"duration,omitempty" example:"320"`
	Year     int    `json:"year,omitempty" example:"2001"`
}

// ActivityEventDTO is a social activity feed entry.
type ActivityEventDTO struct {
	ID          string          `json:"id"`
	UserID      string          `json:"userId"`
	Username    string          `json:"username" example:"bob"`
	DisplayName string          `json:"displayName,omitempty" example:"Bob Marley"`
	Type        string          `json:"type" example:"listen"`
	ItemType    string          `json:"itemType" example:"track"`
	ItemID      string          `json:"itemId"`
	Privacy     string          `json:"privacy" example:"friends"`
	CreatedAt   string          `json:"createdAt" example:"2026-06-15T09:00:00Z"`
	Item        ActivityItemDTO `json:"item,omitempty"`
}

// LibraryStatsDTO is a snapshot of the library analytics.
type LibraryStatsDTO struct {
	Artists       int    `json:"artists" example:"42"`
	Albums        int    `json:"albums" example:"128"`
	Tracks        int    `json:"tracks" example:"1560"`
	TotalSize     int64  `json:"totalSize" example:"9663676416"`
	TotalDuration int64  `json:"totalDuration" example:"432000"`
	UpdatedAt     string `json:"updatedAt" example:"2026-06-17T09:00:00Z"`
}

// ImportItemDTO is one source track and the outcome of resolving it.
type ImportItemDTO struct {
	ID             string `json:"id"`
	Position       int    `json:"position"`
	SourceTitle    string `json:"sourceTitle" example:"Da Funk"`
	SourceArtist   string `json:"sourceArtist" example:"Daft Punk"`
	SourceAlbum    string `json:"sourceAlbum,omitempty"`
	Status         string `json:"status" example:"matched"`
	MatchedTrackID string `json:"matchedTrackId,omitempty"`
	// CandidateTrackID / CandidateCoverArt let a client preview a doubtful item:
	// play the candidate (stream accepts the remote track id) and show its cover.
	CandidateTrackID  string  `json:"candidateTrackId,omitempty"`
	CandidateCoverArt string  `json:"candidateCoverArt,omitempty"`
	ResolvedTitle     string  `json:"resolvedTitle,omitempty"`
	ResolvedArtist    string  `json:"resolvedArtist,omitempty"`
	Confidence        float64 `json:"confidence" example:"0.62"`
	Note              string  `json:"note,omitempty"`
}

// ImportDTO is a playlist-import job (with items on a detail fetch).
type ImportDTO struct {
	ID                 string          `json:"id"`
	Source             string          `json:"source" example:"spotify"`
	SourceRef          string          `json:"sourceRef"`
	SourcePlaylistName string          `json:"sourcePlaylistName,omitempty"`
	PlaylistID         string          `json:"playlistId,omitempty"`
	Status             string          `json:"status" example:"completed"`
	Total              int             `json:"total" example:"42"`
	Matched            int             `json:"matched" example:"38"`
	Doubtful           int             `json:"doubtful" example:"2"`
	Missing            int             `json:"missing" example:"2"`
	Failed             int             `json:"failed" example:"0"`
	Error              string          `json:"error,omitempty"`
	Items              []ImportItemDTO `json:"items,omitempty"`
}

// ImportSourceDTO describes an available import source.
type ImportSourceDTO struct {
	Name       string `json:"name" example:"spotify"`
	Configured bool   `json:"configured" example:"true"`
}

// ProfilePlaylistDTO is a public playlist shown on a user's profile.
type ProfilePlaylistDTO struct {
	ID        string   `json:"id"`
	Name      string   `json:"name" example:"Summer vibes"`
	Comment   string   `json:"comment,omitempty"`
	SongCount int      `json:"songCount" example:"24"`
	Duration  int      `json:"duration" example:"5400"`
	CoverArts []string `json:"coverArts,omitempty"`
}

// ProfileDTO is a user's public profile: identity, visible activity and public
// playlists.
type ProfileDTO struct {
	User struct {
		ID          string `json:"id"`
		Username    string `json:"username" example:"bob"`
		DisplayName string `json:"displayName,omitempty" example:"Bob Marley"`
		IsAdmin     bool   `json:"isAdmin" example:"false"`
	} `json:"user"`
	IsSelf    bool                 `json:"isSelf" example:"false"`
	IsFriend  bool                 `json:"isFriend" example:"true"`
	Activity  []ActivityEventDTO   `json:"activity"`
	Playlists []ProfilePlaylistDTO `json:"playlists"`
}

// JamSessionDTO is the shared state of a synchronized listening session.
type JamSessionDTO struct {
	ID             string   `json:"id"`
	HostID         string   `json:"hostId"`
	Name           string   `json:"name" example:"Friday Night"`
	CurrentTrackID string   `json:"currentTrackId,omitempty"`
	PositionMs     int64    `json:"position" example:"42000"`
	State          string   `json:"state" example:"playing"`
	TrackIDs       []string `json:"trackIds"`
}

// JamParticipantDTO is a member of a jam session.
type JamParticipantDTO struct {
	SessionID string `json:"sessionId"`
	UserID    string `json:"userId"`
	Username  string `json:"username" example:"bob"`
	JoinedAt  string `json:"joinedAt" example:"2026-06-15T09:00:00Z"`
}

// JamDTO wraps a jam session and its participants.
type JamDTO struct {
	Session      JamSessionDTO       `json:"session"`
	Participants []JamParticipantDTO `json:"participants"`
}

// PublicPlaylistDTO is a public playlist available to subscribe to.
type PublicPlaylistDTO struct {
	ID         string   `json:"id"`
	Name       string   `json:"name" example:"Editorial Picks"`
	Owner      string   `json:"owner" example:"alice"`
	Comment    string   `json:"comment,omitempty"`
	SongCount  int      `json:"songCount"`
	Duration   int      `json:"duration"`
	CoverArts  []string `json:"coverArts,omitempty"`
	Subscribed bool     `json:"subscribed"`
}

// LoginDTO is returned by POST /auth/sessions.
type LoginDTO struct {
	Token  string    `json:"token" example:"eyJhbGciOiJIUzI1Ni..."`
	Device DeviceDTO `json:"device"`
}

// DeviceDTO is a device session.
type DeviceDTO struct {
	ID        string `json:"id"`
	Name      string `json:"name" example:"Pixel 8"`
	UserAgent string `json:"userAgent,omitempty"`
	LastSeen  string `json:"lastSeen,omitempty"`
	LastIP    string `json:"lastIp,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	ExpiresAt string `json:"expiresAt,omitempty"`
}

// APITokenDTO is a personal access token (without its secret).
type APITokenDTO struct {
	ID         string `json:"id"`
	Name       string `json:"name" example:"my-cli"`
	Prefix     string `json:"prefix" example:"gsk_AbC12"`
	CreatedAt  string `json:"createdAt" example:"2026-06-15T09:00:00Z"`
	LastUsedAt string `json:"lastUsedAt,omitempty"`
	ExpiresAt  string `json:"expiresAt,omitempty"`
}

// CreateTokenDTO is returned once when a token is created; "token" is the secret
// and is never shown again.
type CreateTokenDTO struct {
	Token  string `json:"token" example:"gsk_AbC12...full-secret"`
	ID     string `json:"id"`
	Name   string `json:"name" example:"my-cli"`
	Prefix string `json:"prefix" example:"gsk_AbC12"`
}
