// Package hub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package hub

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes  bearerAuthContextKey  = "BearerAuth.Scopes"
	InstanceKeyScopes instanceKeyContextKey = "InstanceKey.Scopes"
)

// AccountAuthResponse defines model for account.AuthResponse.
type AccountAuthResponse struct {
	Ok    *bool           `json:"ok,omitempty"`
	Token *string         `json:"token,omitempty"`
	User  *AccountUserDTO `json:"user,omitempty"`
}

// AccountCredentialsRequest defines model for account.CredentialsRequest.
type AccountCredentialsRequest struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// AccountInstanceDTO defines model for account.InstanceDTO.
type AccountInstanceDTO struct {
	CreatedAt *string `json:"createdAt,omitempty"`

	// Id fixed public key (X-Instance-ID)
	Id               *string `json:"id,omitempty"`
	LastSeenAt       *string `json:"lastSeenAt,omitempty"`
	Name             *string `json:"name,omitempty"`
	OptInIngest      *bool   `json:"optInIngest,omitempty"`
	PrivateKeyPrefix *string `json:"privateKeyPrefix,omitempty"`
	Region           *string `json:"region,omitempty"`
	Revoked          *bool   `json:"revoked,omitempty"`
	RevokedAt        *string `json:"revokedAt,omitempty"`
	RotatedAt        *string `json:"rotatedAt,omitempty"`

	// Sqid editable unique handle
	Sqid    *string `json:"sqid,omitempty"`
	Version *string `json:"version,omitempty"`
}

// AccountInstanceKeyResponse defines model for account.InstanceKeyResponse.
type AccountInstanceKeyResponse struct {
	Instance   *AccountInstanceDTO `json:"instance,omitempty"`
	Ok         *bool               `json:"ok,omitempty"`
	PrivateKey *string             `json:"privateKey,omitempty"`
}

// AccountInstanceResponse defines model for account.InstanceResponse.
type AccountInstanceResponse struct {
	Instance *AccountInstanceDTO `json:"instance,omitempty"`
	Ok       *bool               `json:"ok,omitempty"`
}

// AccountInstancesResponse defines model for account.InstancesResponse.
type AccountInstancesResponse struct {
	Instances *[]AccountInstanceDTO `json:"instances,omitempty"`
	Ok        *bool                 `json:"ok,omitempty"`
}

// AccountMeResponse defines model for account.MeResponse.
type AccountMeResponse struct {
	Ok   *bool           `json:"ok,omitempty"`
	User *AccountUserDTO `json:"user,omitempty"`
}

// AccountUpdateInstanceRequest defines model for account.UpdateInstanceRequest.
type AccountUpdateInstanceRequest struct {
	Name        *string `json:"name,omitempty"`
	OptInIngest *bool   `json:"optInIngest,omitempty"`
	Region      *string `json:"region,omitempty"`
}

// AccountUserDTO defines model for account.UserDTO.
type AccountUserDTO struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	Email     *string `json:"email,omitempty"`
	Id        *string `json:"id,omitempty"`
}

// AdminEditorialPlaylistDTO defines model for admin.EditorialPlaylistDTO.
type AdminEditorialPlaylistDTO struct {
	CreatedAt   *string                   `json:"createdAt,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Etag        *string                   `json:"etag,omitempty"`
	Id          *string                   `json:"id,omitempty"`
	Image       *string                   `json:"image,omitempty"`
	Language    *string                   `json:"language,omitempty"`
	Published   *bool                     `json:"published,omitempty"`
	PublishedAt *string                   `json:"publishedAt,omitempty"`
	Region      *string                   `json:"region,omitempty"`
	Slug        *string                   `json:"slug,omitempty"`
	Title       *string                   `json:"title,omitempty"`
	Tracks      *[]AdminEditorialTrackDTO `json:"tracks,omitempty"`
	UpdatedAt   *string                   `json:"updatedAt,omitempty"`
	Version     *int                      `json:"version,omitempty"`
}

// AdminEditorialTrackDTO defines model for admin.EditorialTrackDTO.
type AdminEditorialTrackDTO struct {
	Album    *string `json:"album,omitempty"`
	Artist   *string `json:"artist,omitempty"`
	Duration *int    `json:"duration,omitempty"`
	Image    *string `json:"image,omitempty"`
	Key      *string `json:"key,omitempty"`
	Mbid     *string `json:"mbid,omitempty"`
	Position *int    `json:"position,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// AdminPlaylistRequest defines model for admin.PlaylistRequest.
type AdminPlaylistRequest struct {
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Language    *string `json:"language,omitempty"`
	Region      *string `json:"region,omitempty"`
	Slug        *string `json:"slug,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// AdminPlaylistResponse defines model for admin.PlaylistResponse.
type AdminPlaylistResponse struct {
	Ok       *bool                      `json:"ok,omitempty"`
	Playlist *AdminEditorialPlaylistDTO `json:"playlist,omitempty"`
}

// AdminPlaylistsResponse defines model for admin.PlaylistsResponse.
type AdminPlaylistsResponse struct {
	Ok        *bool                        `json:"ok,omitempty"`
	Playlists *[]AdminEditorialPlaylistDTO `json:"playlists,omitempty"`
}

// AdminPublishStateResponse defines model for admin.PublishStateResponse.
type AdminPublishStateResponse struct {
	Ok        *bool `json:"ok,omitempty"`
	Published *bool `json:"published,omitempty"`
}

// AdminRecomputeResponse defines model for admin.RecomputeResponse.
type AdminRecomputeResponse struct {
	Ok         *bool `json:"ok,omitempty"`
	Recomputed *bool `json:"recomputed,omitempty"`
}

// AdminRunDTO defines model for admin.RunDTO.
type AdminRunDTO struct {
	Algorithm  *string                 `json:"algorithm,omitempty"`
	Error      *string                 `json:"error,omitempty"`
	FinishedAt *string                 `json:"finishedAt,omitempty"`
	Id         *string                 `json:"id,omitempty"`
	Params     *map[string]interface{} `json:"params,omitempty"`
	StartedAt  *string                 `json:"startedAt,omitempty"`
	Stats      *map[string]interface{} `json:"stats,omitempty"`
	Status     *string                 `json:"status,omitempty"`
}

// AdminRunResponse defines model for admin.RunResponse.
type AdminRunResponse struct {
	Ok  *bool        `json:"ok,omitempty"`
	Run *AdminRunDTO `json:"run,omitempty"`
}

// AdminRunsResponse defines model for admin.RunsResponse.
type AdminRunsResponse struct {
	Ok   *bool          `json:"ok,omitempty"`
	Runs *[]AdminRunDTO `json:"runs,omitempty"`
}

// AdminSetTracksRequest defines model for admin.SetTracksRequest.
type AdminSetTracksRequest struct {
	Tracks *[]AdminTrackInputDoc `json:"tracks,omitempty"`
}

// AdminTrackInputDoc defines model for admin.TrackInputDoc.
type AdminTrackInputDoc struct {
	Album    *string `json:"album,omitempty"`
	Artist   *string `json:"artist,omitempty"`
	Duration *int    `json:"duration,omitempty"`
	Image    *string `json:"image,omitempty"`
	Mbid     *string `json:"mbid,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// HttpxDeletedResponse defines model for httpx.DeletedResponse.
type HttpxDeletedResponse struct {
	Deleted *bool `json:"deleted,omitempty"`
	Ok      *bool `json:"ok,omitempty"`
}

// HttpxErrorResponse defines model for httpx.ErrorResponse.
type HttpxErrorResponse struct {
	Error *string `json:"error,omitempty"`
	Ok    *bool   `json:"ok,omitempty"`
}

// HttpxRevokedResponse defines model for httpx.RevokedResponse.
type HttpxRevokedResponse struct {
	Ok      *bool `json:"ok,omitempty"`
	Revoked *bool `json:"revoked,omitempty"`
}

// PublicBootstrapRequest defines model for public.BootstrapRequest.
type PublicBootstrapRequest struct {
	Name        *string `json:"name,omitempty"`
	OptInIngest *bool   `json:"optInIngest,omitempty"`
	Region      *string `json:"region,omitempty"`
	UserId      *string `json:"userId,omitempty"`
	Version     *string `json:"version,omitempty"`
}

// PublicBootstrapResponse defines model for public.BootstrapResponse.
type PublicBootstrapResponse struct {
	CreatedAt *string `json:"createdAt,omitempty"`

	// Id fixed public key → X-Instance-ID
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Ok          *bool   `json:"ok,omitempty"`
	OptInIngest *bool   `json:"optInIngest,omitempty"`

	// PrivateKey shown once
	PrivateKey *string `json:"privateKey,omitempty"`
	Region     *string `json:"region,omitempty"`

	// Sqid editable unique handle
	Sqid *string `json:"sqid,omitempty"`
}

// PublicCoplayItemDoc defines model for public.CoplayItemDoc.
type PublicCoplayItemDoc struct {
	A     *PublicTrackRefDoc `json:"a,omitempty"`
	B     *PublicTrackRefDoc `json:"b,omitempty"`
	Count *int               `json:"count,omitempty"`
}

// PublicCoplaysRequest defines model for public.CoplaysRequest.
type PublicCoplaysRequest struct {
	Coplays *[]PublicCoplayItemDoc `json:"coplays,omitempty"`
}

// PublicDistributionPlaylist defines model for public.DistributionPlaylist.
type PublicDistributionPlaylist struct {
	Comment     *string                    `json:"comment,omitempty"`
	Description *string                    `json:"description,omitempty"`
	Etag        *string                    `json:"etag,omitempty"`
	Id          *string                    `json:"id,omitempty"`
	Image       *string                    `json:"image,omitempty"`
	Kind        *string                    `json:"kind,omitempty"`
	Language    *string                    `json:"language,omitempty"`
	Name        *string                    `json:"name,omitempty"`
	Region      *string                    `json:"region,omitempty"`
	Slug        *string                    `json:"slug,omitempty"`
	Tracks      *[]PublicDistributionTrack `json:"tracks,omitempty"`
	UpdatedAt   *string                    `json:"updatedAt,omitempty"`
	Version     *int                       `json:"version,omitempty"`
}

// PublicDistributionTrack defines model for public.DistributionTrack.
type PublicDistributionTrack struct {
	Album  *string `json:"album,omitempty"`
	Artist *string `json:"artist,omitempty"`
	Image  *string `json:"image,omitempty"`
	Key    *string `json:"key,omitempty"`
	Mbid   *string `json:"mbid,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// PublicIngestResultResponse defines model for public.IngestResultResponse.
type PublicIngestResultResponse struct {
	Accepted *int  `json:"accepted,omitempty"`
	Ok       *bool `json:"ok,omitempty"`
	Received *int  `json:"received,omitempty"`
}

// PublicInstanceProfile defines model for public.InstanceProfile.
type PublicInstanceProfile struct {
	CreatedAt *string `json:"createdAt,omitempty"`

	// Id fixed public key → X-Instance-ID
	Id          *string `json:"id,omitempty"`
	LastSeenAt  *string `json:"lastSeenAt,omitempty"`
	Name        *string `json:"name,omitempty"`
	OptInIngest *bool   `json:"optInIngest,omitempty"`
	Region      *string `json:"region,omitempty"`

	// Sqid editable unique handle
	Sqid    *string `json:"sqid,omitempty"`
	Version *string `json:"version,omitempty"`
}

// PublicPlayItemDoc defines model for public.PlayItemDoc.
type PublicPlayItemDoc struct {
	Album  *string `json:"album,omitempty"`
	Artist *string `json:"artist,omitempty"`
	Count  *int    `json:"count,omitempty"`
	Image  *string `json:"image,omitempty"`
	Mbid   *string `json:"mbid,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// PublicPlaysRequest defines model for public.PlaysRequest.
type PublicPlaysRequest struct {
	Plays *[]PublicPlayItemDoc `json:"plays,omitempty"`
}

// PublicProfileResponse defines model for public.ProfileResponse.
type PublicProfileResponse struct {
	Instance *PublicInstanceProfile `json:"instance,omitempty"`
	Ok       *bool                  `json:"ok,omitempty"`
}

// PublicRegisterRequest defines model for public.RegisterRequest.
type PublicRegisterRequest struct {
	Version *string `json:"version,omitempty"`
}

// PublicScrobbleAggregateDoc defines model for public.ScrobbleAggregateDoc.
type PublicScrobbleAggregateDoc struct {
	Count     *int    `json:"count,omitempty"`
	TrackHash *string `json:"trackHash,omitempty"`
}

// PublicScrobblesRequest defines model for public.ScrobblesRequest.
type PublicScrobblesRequest struct {
	Aggregates *[]PublicScrobbleAggregateDoc `json:"aggregates,omitempty"`
}

// PublicSpotifyImportRequest defines model for public.SpotifyImportRequest.
type PublicSpotifyImportRequest struct {
	Playlist *string `json:"playlist,omitempty"`
}

// PublicSpotifyJobResponse defines model for public.SpotifyJobResponse.
type PublicSpotifyJobResponse struct {
	CreatedAt   *string                    `json:"createdAt,omitempty"`
	Error       *string                    `json:"error,omitempty"`
	FinishedAt  *string                    `json:"finishedAt,omitempty"`
	JobId       *string                    `json:"jobId,omitempty"`
	Ok          *bool                      `json:"ok,omitempty"`
	Playlist    *PublicSpotifyPlaylistMeta `json:"playlist,omitempty"`
	PlaylistId  *string                    `json:"playlistId,omitempty"`
	PlaylistRef *string                    `json:"playlistRef,omitempty"`
	StartedAt   *string                    `json:"startedAt,omitempty"`

	// Status pending | in_progress | completed | failed
	Status     *string               `json:"status,omitempty"`
	TrackCount *int                  `json:"trackCount,omitempty"`
	Tracks     *[]PublicSpotifyTrack `json:"tracks,omitempty"`
}

// PublicSpotifyPlaylistMeta defines model for public.SpotifyPlaylistMeta.
type PublicSpotifyPlaylistMeta struct {
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	Name        *string `json:"name,omitempty"`
	Owner       *string `json:"owner,omitempty"`
}

// PublicSpotifyTrack defines model for public.SpotifyTrack.
type PublicSpotifyTrack struct {
	Album     *string `json:"album,omitempty"`
	Artist    *string `json:"artist,omitempty"`
	Duration  *int    `json:"duration,omitempty"`
	Image     *string `json:"image,omitempty"`
	Key       *string `json:"key,omitempty"`
	SpotifyId *string `json:"spotifyId,omitempty"`
	Title     *string `json:"title,omitempty"`
}

// PublicTrackRefDoc defines model for public.TrackRefDoc.
type PublicTrackRefDoc struct {
	Album  *string `json:"album,omitempty"`
	Artist *string `json:"artist,omitempty"`
	Image  *string `json:"image,omitempty"`
	Mbid   *string `json:"mbid,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// PublicUpdateInstanceRequest defines model for public.UpdateInstanceRequest.
type PublicUpdateInstanceRequest struct {
	Name        *string `json:"name,omitempty"`
	OptInIngest *bool   `json:"optInIngest,omitempty"`
	Sqid        *string `json:"sqid,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// PatchAccountInstancesIdJSONBody defines parameters for PatchAccountInstancesId.
type PatchAccountInstancesIdJSONBody struct {
	union json.RawMessage
}

// PatchAccountInstancesIdJSONBody0 defines parameters for PatchAccountInstancesId.
type PatchAccountInstancesIdJSONBody0 = map[string]interface{}

// PostAccountLoginJSONBody defines parameters for PostAccountLogin.
type PostAccountLoginJSONBody struct {
	union json.RawMessage
}

// PostAccountLoginJSONBody0 defines parameters for PostAccountLogin.
type PostAccountLoginJSONBody0 = map[string]interface{}

// PostAccountRegisterJSONBody defines parameters for PostAccountRegister.
type PostAccountRegisterJSONBody struct {
	union json.RawMessage
}

// PostAccountRegisterJSONBody0 defines parameters for PostAccountRegister.
type PostAccountRegisterJSONBody0 = map[string]interface{}

// PostAdminPlaylistsJSONBody defines parameters for PostAdminPlaylists.
type PostAdminPlaylistsJSONBody struct {
	union json.RawMessage
}

// PostAdminPlaylistsJSONBody0 defines parameters for PostAdminPlaylists.
type PostAdminPlaylistsJSONBody0 = map[string]interface{}

// PatchAdminPlaylistsIdJSONBody defines parameters for PatchAdminPlaylistsId.
type PatchAdminPlaylistsIdJSONBody struct {
	union json.RawMessage
}

// PatchAdminPlaylistsIdJSONBody0 defines parameters for PatchAdminPlaylistsId.
type PatchAdminPlaylistsIdJSONBody0 = map[string]interface{}

// PutAdminPlaylistsIdTracksJSONBody defines parameters for PutAdminPlaylistsIdTracks.
type PutAdminPlaylistsIdTracksJSONBody struct {
	union json.RawMessage
}

// PutAdminPlaylistsIdTracksJSONBody0 defines parameters for PutAdminPlaylistsIdTracks.
type PutAdminPlaylistsIdTracksJSONBody0 = map[string]interface{}

// PostApiV1CoplaysJSONBody defines parameters for PostApiV1Coplays.
type PostApiV1CoplaysJSONBody struct {
	union json.RawMessage
}

// PostApiV1CoplaysJSONBody0 defines parameters for PostApiV1Coplays.
type PostApiV1CoplaysJSONBody0 = map[string]interface{}

// PostApiV1InstancesJSONBody defines parameters for PostApiV1Instances.
type PostApiV1InstancesJSONBody struct {
	union json.RawMessage
}

// PostApiV1InstancesJSONBody0 defines parameters for PostApiV1Instances.
type PostApiV1InstancesJSONBody0 = map[string]interface{}

// PatchApiV1InstancesMeJSONBody defines parameters for PatchApiV1InstancesMe.
type PatchApiV1InstancesMeJSONBody struct {
	union json.RawMessage
}

// PatchApiV1InstancesMeJSONBody0 defines parameters for PatchApiV1InstancesMe.
type PatchApiV1InstancesMeJSONBody0 = map[string]interface{}

// PostApiV1InstancesRegisterJSONBody defines parameters for PostApiV1InstancesRegister.
type PostApiV1InstancesRegisterJSONBody struct {
	union json.RawMessage
}

// PostApiV1InstancesRegisterJSONBody0 defines parameters for PostApiV1InstancesRegister.
type PostApiV1InstancesRegisterJSONBody0 = map[string]interface{}

// GetApiV1PlaylistsParams defines parameters for GetApiV1Playlists.
type GetApiV1PlaylistsParams struct {
	// Region Narrow to a region (defaults to the instance's region)
	Region *string `form:"region,omitempty" json:"region,omitempty"`

	// IfNoneMatch Collection ETag for conditional GET
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// IfModifiedSince RFC1123 date for conditional GET
	IfModifiedSince *string `json:"If-Modified-Since,omitempty"`
}

// GetApiV1PlaylistsSlugParams defines parameters for GetApiV1PlaylistsSlug.
type GetApiV1PlaylistsSlugParams struct {
	// IfNoneMatch Playlist ETag for conditional GET
	IfNoneMatch *string `json:"If-None-Match,omitempty"`

	// IfModifiedSince RFC1123 date for conditional GET
	IfModifiedSince *string `json:"If-Modified-Since,omitempty"`
}

// PostApiV1PlaysJSONBody defines parameters for PostApiV1Plays.
type PostApiV1PlaysJSONBody struct {
	union json.RawMessage
}

// PostApiV1PlaysJSONBody0 defines parameters for PostApiV1Plays.
type PostApiV1PlaysJSONBody0 = map[string]interface{}

// PostApiV1ScrobblesJSONBody defines parameters for PostApiV1Scrobbles.
type PostApiV1ScrobblesJSONBody struct {
	union json.RawMessage
}

// PostApiV1ScrobblesJSONBody0 defines parameters for PostApiV1Scrobbles.
type PostApiV1ScrobblesJSONBody0 = map[string]interface{}

// PostApiV1SpotifyImportsJSONBody defines parameters for PostApiV1SpotifyImports.
type PostApiV1SpotifyImportsJSONBody struct {
	union json.RawMessage
}

// PostApiV1SpotifyImportsJSONBody0 defines parameters for PostApiV1SpotifyImports.
type PostApiV1SpotifyImportsJSONBody0 = map[string]interface{}

// PatchAccountInstancesIdJSONRequestBody defines body for PatchAccountInstancesId for application/json ContentType.
type PatchAccountInstancesIdJSONRequestBody PatchAccountInstancesIdJSONBody

// PostAccountLoginJSONRequestBody defines body for PostAccountLogin for application/json ContentType.
type PostAccountLoginJSONRequestBody PostAccountLoginJSONBody

// PostAccountRegisterJSONRequestBody defines body for PostAccountRegister for application/json ContentType.
type PostAccountRegisterJSONRequestBody PostAccountRegisterJSONBody

// PostAdminPlaylistsJSONRequestBody defines body for PostAdminPlaylists for application/json ContentType.
type PostAdminPlaylistsJSONRequestBody PostAdminPlaylistsJSONBody

// PatchAdminPlaylistsIdJSONRequestBody defines body for PatchAdminPlaylistsId for application/json ContentType.
type PatchAdminPlaylistsIdJSONRequestBody PatchAdminPlaylistsIdJSONBody

// PutAdminPlaylistsIdTracksJSONRequestBody defines body for PutAdminPlaylistsIdTracks for application/json ContentType.
type PutAdminPlaylistsIdTracksJSONRequestBody PutAdminPlaylistsIdTracksJSONBody

// PostApiV1CoplaysJSONRequestBody defines body for PostApiV1Coplays for application/json ContentType.
type PostApiV1CoplaysJSONRequestBody PostApiV1CoplaysJSONBody

// PostApiV1InstancesJSONRequestBody defines body for PostApiV1Instances for application/json ContentType.
type PostApiV1InstancesJSONRequestBody PostApiV1InstancesJSONBody

// PatchApiV1InstancesMeJSONRequestBody defines body for PatchApiV1InstancesMe for application/json ContentType.
type PatchApiV1InstancesMeJSONRequestBody PatchApiV1InstancesMeJSONBody

// PostApiV1InstancesRegisterJSONRequestBody defines body for PostApiV1InstancesRegister for application/json ContentType.
type PostApiV1InstancesRegisterJSONRequestBody PostApiV1InstancesRegisterJSONBody

// PostApiV1PlaysJSONRequestBody defines body for PostApiV1Plays for application/json ContentType.
type PostApiV1PlaysJSONRequestBody PostApiV1PlaysJSONBody

// PostApiV1ScrobblesJSONRequestBody defines body for PostApiV1Scrobbles for application/json ContentType.
type PostApiV1ScrobblesJSONRequestBody PostApiV1ScrobblesJSONBody

// PostApiV1SpotifyImportsJSONRequestBody defines body for PostApiV1SpotifyImports for application/json ContentType.
type PostApiV1SpotifyImportsJSONRequestBody PostApiV1SpotifyImportsJSONBody

// AsPatchAccountInstancesIdJSONBody0 returns the union data inside the PatchAccountInstancesIdJSONBody as a PatchAccountInstancesIdJSONBody0
func (t PatchAccountInstancesIdJSONBody) AsPatchAccountInstancesIdJSONBody0() (PatchAccountInstancesIdJSONBody0, error) {
	var body PatchAccountInstancesIdJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchAccountInstancesIdJSONBody0 overwrites any union data inside the PatchAccountInstancesIdJSONBody as the provided PatchAccountInstancesIdJSONBody0
func (t *PatchAccountInstancesIdJSONBody) FromPatchAccountInstancesIdJSONBody0(v PatchAccountInstancesIdJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchAccountInstancesIdJSONBody0 performs a merge with any union data inside the PatchAccountInstancesIdJSONBody, using the provided PatchAccountInstancesIdJSONBody0
func (t *PatchAccountInstancesIdJSONBody) MergePatchAccountInstancesIdJSONBody0(v PatchAccountInstancesIdJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccountUpdateInstanceRequest returns the union data inside the PatchAccountInstancesIdJSONBody as a AccountUpdateInstanceRequest
func (t PatchAccountInstancesIdJSONBody) AsAccountUpdateInstanceRequest() (AccountUpdateInstanceRequest, error) {
	var body AccountUpdateInstanceRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountUpdateInstanceRequest overwrites any union data inside the PatchAccountInstancesIdJSONBody as the provided AccountUpdateInstanceRequest
func (t *PatchAccountInstancesIdJSONBody) FromAccountUpdateInstanceRequest(v AccountUpdateInstanceRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountUpdateInstanceRequest performs a merge with any union data inside the PatchAccountInstancesIdJSONBody, using the provided AccountUpdateInstanceRequest
func (t *PatchAccountInstancesIdJSONBody) MergeAccountUpdateInstanceRequest(v AccountUpdateInstanceRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchAccountInstancesIdJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchAccountInstancesIdJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostAccountLoginJSONBody0 returns the union data inside the PostAccountLoginJSONBody as a PostAccountLoginJSONBody0
func (t PostAccountLoginJSONBody) AsPostAccountLoginJSONBody0() (PostAccountLoginJSONBody0, error) {
	var body PostAccountLoginJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostAccountLoginJSONBody0 overwrites any union data inside the PostAccountLoginJSONBody as the provided PostAccountLoginJSONBody0
func (t *PostAccountLoginJSONBody) FromPostAccountLoginJSONBody0(v PostAccountLoginJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostAccountLoginJSONBody0 performs a merge with any union data inside the PostAccountLoginJSONBody, using the provided PostAccountLoginJSONBody0
func (t *PostAccountLoginJSONBody) MergePostAccountLoginJSONBody0(v PostAccountLoginJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccountCredentialsRequest returns the union data inside the PostAccountLoginJSONBody as a AccountCredentialsRequest
func (t PostAccountLoginJSONBody) AsAccountCredentialsRequest() (AccountCredentialsRequest, error) {
	var body AccountCredentialsRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountCredentialsRequest overwrites any union data inside the PostAccountLoginJSONBody as the provided AccountCredentialsRequest
func (t *PostAccountLoginJSONBody) FromAccountCredentialsRequest(v AccountCredentialsRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountCredentialsRequest performs a merge with any union data inside the PostAccountLoginJSONBody, using the provided AccountCredentialsRequest
func (t *PostAccountLoginJSONBody) MergeAccountCredentialsRequest(v AccountCredentialsRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostAccountLoginJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostAccountLoginJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostAccountRegisterJSONBody0 returns the union data inside the PostAccountRegisterJSONBody as a PostAccountRegisterJSONBody0
func (t PostAccountRegisterJSONBody) AsPostAccountRegisterJSONBody0() (PostAccountRegisterJSONBody0, error) {
	var body PostAccountRegisterJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostAccountRegisterJSONBody0 overwrites any union data inside the PostAccountRegisterJSONBody as the provided PostAccountRegisterJSONBody0
func (t *PostAccountRegisterJSONBody) FromPostAccountRegisterJSONBody0(v PostAccountRegisterJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostAccountRegisterJSONBody0 performs a merge with any union data inside the PostAccountRegisterJSONBody, using the provided PostAccountRegisterJSONBody0
func (t *PostAccountRegisterJSONBody) MergePostAccountRegisterJSONBody0(v PostAccountRegisterJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccountCredentialsRequest returns the union data inside the PostAccountRegisterJSONBody as a AccountCredentialsRequest
func (t PostAccountRegisterJSONBody) AsAccountCredentialsRequest() (AccountCredentialsRequest, error) {
	var body AccountCredentialsRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountCredentialsRequest overwrites any union data inside the PostAccountRegisterJSONBody as the provided AccountCredentialsRequest
func (t *PostAccountRegisterJSONBody) FromAccountCredentialsRequest(v AccountCredentialsRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountCredentialsRequest performs a merge with any union data inside the PostAccountRegisterJSONBody, using the provided AccountCredentialsRequest
func (t *PostAccountRegisterJSONBody) MergeAccountCredentialsRequest(v AccountCredentialsRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostAccountRegisterJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostAccountRegisterJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostAdminPlaylistsJSONBody0 returns the union data inside the PostAdminPlaylistsJSONBody as a PostAdminPlaylistsJSONBody0
func (t PostAdminPlaylistsJSONBody) AsPostAdminPlaylistsJSONBody0() (PostAdminPlaylistsJSONBody0, error) {
	var body PostAdminPlaylistsJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostAdminPlaylistsJSONBody0 overwrites any union data inside the PostAdminPlaylistsJSONBody as the provided PostAdminPlaylistsJSONBody0
func (t *PostAdminPlaylistsJSONBody) FromPostAdminPlaylistsJSONBody0(v PostAdminPlaylistsJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostAdminPlaylistsJSONBody0 performs a merge with any union data inside the PostAdminPlaylistsJSONBody, using the provided PostAdminPlaylistsJSONBody0
func (t *PostAdminPlaylistsJSONBody) MergePostAdminPlaylistsJSONBody0(v PostAdminPlaylistsJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdminPlaylistRequest returns the union data inside the PostAdminPlaylistsJSONBody as a AdminPlaylistRequest
func (t PostAdminPlaylistsJSONBody) AsAdminPlaylistRequest() (AdminPlaylistRequest, error) {
	var body AdminPlaylistRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminPlaylistRequest overwrites any union data inside the PostAdminPlaylistsJSONBody as the provided AdminPlaylistRequest
func (t *PostAdminPlaylistsJSONBody) FromAdminPlaylistRequest(v AdminPlaylistRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminPlaylistRequest performs a merge with any union data inside the PostAdminPlaylistsJSONBody, using the provided AdminPlaylistRequest
func (t *PostAdminPlaylistsJSONBody) MergeAdminPlaylistRequest(v AdminPlaylistRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostAdminPlaylistsJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostAdminPlaylistsJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPatchAdminPlaylistsIdJSONBody0 returns the union data inside the PatchAdminPlaylistsIdJSONBody as a PatchAdminPlaylistsIdJSONBody0
func (t PatchAdminPlaylistsIdJSONBody) AsPatchAdminPlaylistsIdJSONBody0() (PatchAdminPlaylistsIdJSONBody0, error) {
	var body PatchAdminPlaylistsIdJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchAdminPlaylistsIdJSONBody0 overwrites any union data inside the PatchAdminPlaylistsIdJSONBody as the provided PatchAdminPlaylistsIdJSONBody0
func (t *PatchAdminPlaylistsIdJSONBody) FromPatchAdminPlaylistsIdJSONBody0(v PatchAdminPlaylistsIdJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchAdminPlaylistsIdJSONBody0 performs a merge with any union data inside the PatchAdminPlaylistsIdJSONBody, using the provided PatchAdminPlaylistsIdJSONBody0
func (t *PatchAdminPlaylistsIdJSONBody) MergePatchAdminPlaylistsIdJSONBody0(v PatchAdminPlaylistsIdJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdminPlaylistRequest returns the union data inside the PatchAdminPlaylistsIdJSONBody as a AdminPlaylistRequest
func (t PatchAdminPlaylistsIdJSONBody) AsAdminPlaylistRequest() (AdminPlaylistRequest, error) {
	var body AdminPlaylistRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminPlaylistRequest overwrites any union data inside the PatchAdminPlaylistsIdJSONBody as the provided AdminPlaylistRequest
func (t *PatchAdminPlaylistsIdJSONBody) FromAdminPlaylistRequest(v AdminPlaylistRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminPlaylistRequest performs a merge with any union data inside the PatchAdminPlaylistsIdJSONBody, using the provided AdminPlaylistRequest
func (t *PatchAdminPlaylistsIdJSONBody) MergeAdminPlaylistRequest(v AdminPlaylistRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchAdminPlaylistsIdJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchAdminPlaylistsIdJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPutAdminPlaylistsIdTracksJSONBody0 returns the union data inside the PutAdminPlaylistsIdTracksJSONBody as a PutAdminPlaylistsIdTracksJSONBody0
func (t PutAdminPlaylistsIdTracksJSONBody) AsPutAdminPlaylistsIdTracksJSONBody0() (PutAdminPlaylistsIdTracksJSONBody0, error) {
	var body PutAdminPlaylistsIdTracksJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPutAdminPlaylistsIdTracksJSONBody0 overwrites any union data inside the PutAdminPlaylistsIdTracksJSONBody as the provided PutAdminPlaylistsIdTracksJSONBody0
func (t *PutAdminPlaylistsIdTracksJSONBody) FromPutAdminPlaylistsIdTracksJSONBody0(v PutAdminPlaylistsIdTracksJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePutAdminPlaylistsIdTracksJSONBody0 performs a merge with any union data inside the PutAdminPlaylistsIdTracksJSONBody, using the provided PutAdminPlaylistsIdTracksJSONBody0
func (t *PutAdminPlaylistsIdTracksJSONBody) MergePutAdminPlaylistsIdTracksJSONBody0(v PutAdminPlaylistsIdTracksJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdminSetTracksRequest returns the union data inside the PutAdminPlaylistsIdTracksJSONBody as a AdminSetTracksRequest
func (t PutAdminPlaylistsIdTracksJSONBody) AsAdminSetTracksRequest() (AdminSetTracksRequest, error) {
	var body AdminSetTracksRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdminSetTracksRequest overwrites any union data inside the PutAdminPlaylistsIdTracksJSONBody as the provided AdminSetTracksRequest
func (t *PutAdminPlaylistsIdTracksJSONBody) FromAdminSetTracksRequest(v AdminSetTracksRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdminSetTracksRequest performs a merge with any union data inside the PutAdminPlaylistsIdTracksJSONBody, using the provided AdminSetTracksRequest
func (t *PutAdminPlaylistsIdTracksJSONBody) MergeAdminSetTracksRequest(v AdminSetTracksRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PutAdminPlaylistsIdTracksJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PutAdminPlaylistsIdTracksJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1CoplaysJSONBody0 returns the union data inside the PostApiV1CoplaysJSONBody as a PostApiV1CoplaysJSONBody0
func (t PostApiV1CoplaysJSONBody) AsPostApiV1CoplaysJSONBody0() (PostApiV1CoplaysJSONBody0, error) {
	var body PostApiV1CoplaysJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1CoplaysJSONBody0 overwrites any union data inside the PostApiV1CoplaysJSONBody as the provided PostApiV1CoplaysJSONBody0
func (t *PostApiV1CoplaysJSONBody) FromPostApiV1CoplaysJSONBody0(v PostApiV1CoplaysJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1CoplaysJSONBody0 performs a merge with any union data inside the PostApiV1CoplaysJSONBody, using the provided PostApiV1CoplaysJSONBody0
func (t *PostApiV1CoplaysJSONBody) MergePostApiV1CoplaysJSONBody0(v PostApiV1CoplaysJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicCoplaysRequest returns the union data inside the PostApiV1CoplaysJSONBody as a PublicCoplaysRequest
func (t PostApiV1CoplaysJSONBody) AsPublicCoplaysRequest() (PublicCoplaysRequest, error) {
	var body PublicCoplaysRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicCoplaysRequest overwrites any union data inside the PostApiV1CoplaysJSONBody as the provided PublicCoplaysRequest
func (t *PostApiV1CoplaysJSONBody) FromPublicCoplaysRequest(v PublicCoplaysRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicCoplaysRequest performs a merge with any union data inside the PostApiV1CoplaysJSONBody, using the provided PublicCoplaysRequest
func (t *PostApiV1CoplaysJSONBody) MergePublicCoplaysRequest(v PublicCoplaysRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1CoplaysJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1CoplaysJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1InstancesJSONBody0 returns the union data inside the PostApiV1InstancesJSONBody as a PostApiV1InstancesJSONBody0
func (t PostApiV1InstancesJSONBody) AsPostApiV1InstancesJSONBody0() (PostApiV1InstancesJSONBody0, error) {
	var body PostApiV1InstancesJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1InstancesJSONBody0 overwrites any union data inside the PostApiV1InstancesJSONBody as the provided PostApiV1InstancesJSONBody0
func (t *PostApiV1InstancesJSONBody) FromPostApiV1InstancesJSONBody0(v PostApiV1InstancesJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1InstancesJSONBody0 performs a merge with any union data inside the PostApiV1InstancesJSONBody, using the provided PostApiV1InstancesJSONBody0
func (t *PostApiV1InstancesJSONBody) MergePostApiV1InstancesJSONBody0(v PostApiV1InstancesJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicBootstrapRequest returns the union data inside the PostApiV1InstancesJSONBody as a PublicBootstrapRequest
func (t PostApiV1InstancesJSONBody) AsPublicBootstrapRequest() (PublicBootstrapRequest, error) {
	var body PublicBootstrapRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicBootstrapRequest overwrites any union data inside the PostApiV1InstancesJSONBody as the provided PublicBootstrapRequest
func (t *PostApiV1InstancesJSONBody) FromPublicBootstrapRequest(v PublicBootstrapRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicBootstrapRequest performs a merge with any union data inside the PostApiV1InstancesJSONBody, using the provided PublicBootstrapRequest
func (t *PostApiV1InstancesJSONBody) MergePublicBootstrapRequest(v PublicBootstrapRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1InstancesJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1InstancesJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPatchApiV1InstancesMeJSONBody0 returns the union data inside the PatchApiV1InstancesMeJSONBody as a PatchApiV1InstancesMeJSONBody0
func (t PatchApiV1InstancesMeJSONBody) AsPatchApiV1InstancesMeJSONBody0() (PatchApiV1InstancesMeJSONBody0, error) {
	var body PatchApiV1InstancesMeJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchApiV1InstancesMeJSONBody0 overwrites any union data inside the PatchApiV1InstancesMeJSONBody as the provided PatchApiV1InstancesMeJSONBody0
func (t *PatchApiV1InstancesMeJSONBody) FromPatchApiV1InstancesMeJSONBody0(v PatchApiV1InstancesMeJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchApiV1InstancesMeJSONBody0 performs a merge with any union data inside the PatchApiV1InstancesMeJSONBody, using the provided PatchApiV1InstancesMeJSONBody0
func (t *PatchApiV1InstancesMeJSONBody) MergePatchApiV1InstancesMeJSONBody0(v PatchApiV1InstancesMeJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicUpdateInstanceRequest returns the union data inside the PatchApiV1InstancesMeJSONBody as a PublicUpdateInstanceRequest
func (t PatchApiV1InstancesMeJSONBody) AsPublicUpdateInstanceRequest() (PublicUpdateInstanceRequest, error) {
	var body PublicUpdateInstanceRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicUpdateInstanceRequest overwrites any union data inside the PatchApiV1InstancesMeJSONBody as the provided PublicUpdateInstanceRequest
func (t *PatchApiV1InstancesMeJSONBody) FromPublicUpdateInstanceRequest(v PublicUpdateInstanceRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicUpdateInstanceRequest performs a merge with any union data inside the PatchApiV1InstancesMeJSONBody, using the provided PublicUpdateInstanceRequest
func (t *PatchApiV1InstancesMeJSONBody) MergePublicUpdateInstanceRequest(v PublicUpdateInstanceRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchApiV1InstancesMeJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchApiV1InstancesMeJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1InstancesRegisterJSONBody0 returns the union data inside the PostApiV1InstancesRegisterJSONBody as a PostApiV1InstancesRegisterJSONBody0
func (t PostApiV1InstancesRegisterJSONBody) AsPostApiV1InstancesRegisterJSONBody0() (PostApiV1InstancesRegisterJSONBody0, error) {
	var body PostApiV1InstancesRegisterJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1InstancesRegisterJSONBody0 overwrites any union data inside the PostApiV1InstancesRegisterJSONBody as the provided PostApiV1InstancesRegisterJSONBody0
func (t *PostApiV1InstancesRegisterJSONBody) FromPostApiV1InstancesRegisterJSONBody0(v PostApiV1InstancesRegisterJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1InstancesRegisterJSONBody0 performs a merge with any union data inside the PostApiV1InstancesRegisterJSONBody, using the provided PostApiV1InstancesRegisterJSONBody0
func (t *PostApiV1InstancesRegisterJSONBody) MergePostApiV1InstancesRegisterJSONBody0(v PostApiV1InstancesRegisterJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicRegisterRequest returns the union data inside the PostApiV1InstancesRegisterJSONBody as a PublicRegisterRequest
func (t PostApiV1InstancesRegisterJSONBody) AsPublicRegisterRequest() (PublicRegisterRequest, error) {
	var body PublicRegisterRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicRegisterRequest overwrites any union data inside the PostApiV1InstancesRegisterJSONBody as the provided PublicRegisterRequest
func (t *PostApiV1InstancesRegisterJSONBody) FromPublicRegisterRequest(v PublicRegisterRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicRegisterRequest performs a merge with any union data inside the PostApiV1InstancesRegisterJSONBody, using the provided PublicRegisterRequest
func (t *PostApiV1InstancesRegisterJSONBody) MergePublicRegisterRequest(v PublicRegisterRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1InstancesRegisterJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1InstancesRegisterJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1PlaysJSONBody0 returns the union data inside the PostApiV1PlaysJSONBody as a PostApiV1PlaysJSONBody0
func (t PostApiV1PlaysJSONBody) AsPostApiV1PlaysJSONBody0() (PostApiV1PlaysJSONBody0, error) {
	var body PostApiV1PlaysJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1PlaysJSONBody0 overwrites any union data inside the PostApiV1PlaysJSONBody as the provided PostApiV1PlaysJSONBody0
func (t *PostApiV1PlaysJSONBody) FromPostApiV1PlaysJSONBody0(v PostApiV1PlaysJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1PlaysJSONBody0 performs a merge with any union data inside the PostApiV1PlaysJSONBody, using the provided PostApiV1PlaysJSONBody0
func (t *PostApiV1PlaysJSONBody) MergePostApiV1PlaysJSONBody0(v PostApiV1PlaysJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicPlaysRequest returns the union data inside the PostApiV1PlaysJSONBody as a PublicPlaysRequest
func (t PostApiV1PlaysJSONBody) AsPublicPlaysRequest() (PublicPlaysRequest, error) {
	var body PublicPlaysRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicPlaysRequest overwrites any union data inside the PostApiV1PlaysJSONBody as the provided PublicPlaysRequest
func (t *PostApiV1PlaysJSONBody) FromPublicPlaysRequest(v PublicPlaysRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicPlaysRequest performs a merge with any union data inside the PostApiV1PlaysJSONBody, using the provided PublicPlaysRequest
func (t *PostApiV1PlaysJSONBody) MergePublicPlaysRequest(v PublicPlaysRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1PlaysJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1PlaysJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1ScrobblesJSONBody0 returns the union data inside the PostApiV1ScrobblesJSONBody as a PostApiV1ScrobblesJSONBody0
func (t PostApiV1ScrobblesJSONBody) AsPostApiV1ScrobblesJSONBody0() (PostApiV1ScrobblesJSONBody0, error) {
	var body PostApiV1ScrobblesJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1ScrobblesJSONBody0 overwrites any union data inside the PostApiV1ScrobblesJSONBody as the provided PostApiV1ScrobblesJSONBody0
func (t *PostApiV1ScrobblesJSONBody) FromPostApiV1ScrobblesJSONBody0(v PostApiV1ScrobblesJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1ScrobblesJSONBody0 performs a merge with any union data inside the PostApiV1ScrobblesJSONBody, using the provided PostApiV1ScrobblesJSONBody0
func (t *PostApiV1ScrobblesJSONBody) MergePostApiV1ScrobblesJSONBody0(v PostApiV1ScrobblesJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicScrobblesRequest returns the union data inside the PostApiV1ScrobblesJSONBody as a PublicScrobblesRequest
func (t PostApiV1ScrobblesJSONBody) AsPublicScrobblesRequest() (PublicScrobblesRequest, error) {
	var body PublicScrobblesRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicScrobblesRequest overwrites any union data inside the PostApiV1ScrobblesJSONBody as the provided PublicScrobblesRequest
func (t *PostApiV1ScrobblesJSONBody) FromPublicScrobblesRequest(v PublicScrobblesRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicScrobblesRequest performs a merge with any union data inside the PostApiV1ScrobblesJSONBody, using the provided PublicScrobblesRequest
func (t *PostApiV1ScrobblesJSONBody) MergePublicScrobblesRequest(v PublicScrobblesRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1ScrobblesJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1ScrobblesJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPostApiV1SpotifyImportsJSONBody0 returns the union data inside the PostApiV1SpotifyImportsJSONBody as a PostApiV1SpotifyImportsJSONBody0
func (t PostApiV1SpotifyImportsJSONBody) AsPostApiV1SpotifyImportsJSONBody0() (PostApiV1SpotifyImportsJSONBody0, error) {
	var body PostApiV1SpotifyImportsJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostApiV1SpotifyImportsJSONBody0 overwrites any union data inside the PostApiV1SpotifyImportsJSONBody as the provided PostApiV1SpotifyImportsJSONBody0
func (t *PostApiV1SpotifyImportsJSONBody) FromPostApiV1SpotifyImportsJSONBody0(v PostApiV1SpotifyImportsJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostApiV1SpotifyImportsJSONBody0 performs a merge with any union data inside the PostApiV1SpotifyImportsJSONBody, using the provided PostApiV1SpotifyImportsJSONBody0
func (t *PostApiV1SpotifyImportsJSONBody) MergePostApiV1SpotifyImportsJSONBody0(v PostApiV1SpotifyImportsJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicSpotifyImportRequest returns the union data inside the PostApiV1SpotifyImportsJSONBody as a PublicSpotifyImportRequest
func (t PostApiV1SpotifyImportsJSONBody) AsPublicSpotifyImportRequest() (PublicSpotifyImportRequest, error) {
	var body PublicSpotifyImportRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicSpotifyImportRequest overwrites any union data inside the PostApiV1SpotifyImportsJSONBody as the provided PublicSpotifyImportRequest
func (t *PostApiV1SpotifyImportsJSONBody) FromPublicSpotifyImportRequest(v PublicSpotifyImportRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicSpotifyImportRequest performs a merge with any union data inside the PostApiV1SpotifyImportsJSONBody, using the provided PublicSpotifyImportRequest
func (t *PostApiV1SpotifyImportsJSONBody) MergePublicSpotifyImportRequest(v PublicSpotifyImportRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostApiV1SpotifyImportsJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PostApiV1SpotifyImportsJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
